version: '3'

## Wiremock
services:
  wiremock:    
    container_name: wiremock
    image: wiremock/wiremock
    ports:
      - "7070:8080"
      - "7443:8443"
networks:
    external-api:
      external: true